<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Jahiduls-MBP.lan" failures="1" tests="1" name="Command line test" time="0.022" errors="0" timestamp="22 Nov 2022 02:54:48 GMT">
  <testcase classname="calculatortest.CalculatorTest" name="addTest" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [22] but found [20]">
      <![CDATA[java.lang.AssertionError: expected [22] but found [20]
	at calculatortest.CalculatorTest.addTest(CalculatorTest.java:15)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- addTest -->
</testsuite> <!-- Command line test -->
